populacao:
  adulto:  
    label: "adulto"
    params: 
        tx_mortalidade: 0.01
        tx_mobilidade: 0.5
        tx_infeccao: 0.3
        tx_nascimento: 0.1
        tx_recuperacao: 0.2
    S: [20,120]
    I: [5,80]
    R: [0,1]

  idoso:  
      label: "idoso"
      params:
          tx_mortalidade: 0.2
          tx_mobilidade: 0.1
          tx_infeccao: 0.5
          tx_nascimento: 0
          tx_recuperacao: 0.01
      S: [20,120]
      I: [5,80]
      R: [0,1]

  crianca:  
      label: "crianca"
      params:
          tx_mortalidade: 0.01
          tx_mobilidade: 0.3
          tx_infeccao: 0.5
          tx_nascimento: 0
          tx_recuperacao: 0.5
      S: [20,120]
      I: [5,80]
      R: [0,1]
config:
  place: "São João del Rei, Minas Gerais, Brazil"
  steps: 365